### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by christoga** [vickydasta/hitungindong#2]
I think the name is too long : hitungindong
I prefer "Matybot" is an excellent name.

**Comment by vickydasta** [comment]
i'll consider that, considering that it's uses Indonesian language as its main language, so i'd rather use hitungindong rather than any *English names

**Comment by christoga** [comment]
Itungbot?

**Comment by vickydasta** [comment]
i may should change its name then, or you can create your own but based on my work, it's no problem anyway.
