### ISSUE TITLE
Useful?

### ISSUE THREAD

**Issue by christoga** [vickydasta/hitungindong#3]
I try to use the command : 
```
$ python bot.py
> bot cariin dua dikali sembilan puluh sembilan
dikali
```
Is it working?
Thanks

**Comment by vickydasta** [comment]
you should read the README.md first, 
it's not about "the calculation" working or not, it's all about how the bot dealing with different sentyments, like what you done to it. 

`bot cariin dua dikali sembilan puluh sembilan` should returns a `dikali` which is an operand,
for multiplying 2 integers, or more. and so on for another operands.
